# Generated by Django 2.2.12 on 2022-05-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='', max_length=7)),
                ('signs_and_symptoms', models.CharField(default='', max_length=255)),
                ('patient_type', models.CharField(default='', max_length=10)),
                ('condition', models.CharField(default='', max_length=255)),
                ('test', models.CharField(default='', max_length=255)),
                ('disease_found', models.CharField(default='', max_length=255)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
