# Generated by Django 2.2.12 on 2022-05-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='condition',
        ),
    ]
